name: workout_tracker_repo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  timeago: ^3.6.0
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.1.1
  firebase_storage: 12.4.5
  flutter_dotenv: ^5.1.0
  cloud_firestore: 5.6.8
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here (correct location)
  assets:
    - .env
    - assets/images/