name: workout_tracker_repo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  timeago: ^3.6.0
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.1.1
  firebase_storage: 12.4.5
  flutter_dotenv: ^5.1.0
  cloud_firestore: 5.6.8
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  dotted_border: ^2.0.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  font_awesome_flutter: ^10.8.0
  path_provider: ^2.0.14
  saver_gallery: ^4.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here (correct location)
  assets:
    - .env
    - assets/images/
    - assets/images/empty-folder.png
    - assets/images/contact_us.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
        - asset: assets/fonts/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter_18pt-LightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-Thin.ttf
        - asset: assets/fonts/Inter_18pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_24pt-Black.ttf
        - asset: assets/fonts/Inter_24pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Italic.ttf
        - asset: assets/fonts/Inter_24pt-Light.ttf
        - asset: assets/fonts/Inter_24pt-LightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Medium.ttf
        - asset: assets/fonts/Inter_24pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
        - asset: assets/fonts/Inter_24pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-Thin.ttf
        - asset: assets/fonts/Inter_24pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_28pt-Black.ttf
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf

