// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQaKjdMMGwaYAHT4sMXcrO2u68ZHdJG8Y',
    appId: '1:683585224838:web:5c6379c015bd10eef51107',
    messagingSenderId: '683585224838',
    projectId: 'workout-app-59927',
    authDomain: 'workout-app-59927.firebaseapp.com',
    storageBucket: 'workout-app-59927.firebasestorage.app',
    measurementId: 'G-T4HWY5HB7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnphWZJbeswW8TqzShu2shN1rKwy9R1gY',
    appId: '1:683585224838:android:1c4b80cceac17e26f51107',
    messagingSenderId: '683585224838',
    projectId: 'workout-app-59927',
    storageBucket: 'workout-app-59927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCglRX2uk4g8rDuevFLNg9HOB6POQLD9dU',
    appId: '1:683585224838:ios:49584abe1cd48b6ef51107',
    messagingSenderId: '683585224838',
    projectId: 'workout-app-59927',
    storageBucket: 'workout-app-59927.firebasestorage.app',
    iosClientId: '683585224838-hi2li8438kl4i22f14s6fb807cav3d12.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutTrackerRepo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCglRX2uk4g8rDuevFLNg9HOB6POQLD9dU',
    appId: '1:683585224838:ios:49584abe1cd48b6ef51107',
    messagingSenderId: '683585224838',
    projectId: 'workout-app-59927',
    storageBucket: 'workout-app-59927.firebasestorage.app',
    iosClientId: '683585224838-hi2li8438kl4i22f14s6fb807cav3d12.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutTrackerRepo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQaKjdMMGwaYAHT4sMXcrO2u68ZHdJG8Y',
    appId: '1:683585224838:web:03784591258d4662f51107',
    messagingSenderId: '683585224838',
    projectId: 'workout-app-59927',
    authDomain: 'workout-app-59927.firebaseapp.com',
    storageBucket: 'workout-app-59927.firebasestorage.app',
    measurementId: 'G-5BW168QYDK',
  );
}
