import 'package:flutter/material.dart';

class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Profile')),
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            children: [
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
              Text('Profile Page'),
            ],
          ),
        ),
      ),
    );
  }
}
