name: Auto Rebase Feature Branch into Beta

on:
  pull_request:
    types: [ closed ]
    branches:
      - beta

jobs:
  rebase-feature:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta branch
        uses: actions / checkout@v3
        with:
          ref: beta
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: |
          git fetch origin +refs/head/*:refs/remotes/origin/*
      - name: Rebase merged feature branch onto beta
        run: |
          git rebase origin/${{github.event.pull_request.head.ref}} || echo "Rebase failed"
          git push origin beta --force-with-lease