name: Auto Rebase Feature Branch

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - beta

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase feature branch onto beta
        run: |
          git fetch origin
          git checkout ${{ github.head_ref }}
          git rebase origin/beta

      - name: Push rebased branch
        run: |
          git push origin ${{ github.head_ref }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}