name: Auto Rebase Feature Branch into Beta

on:
  pull_request:
    types: [ closed ]
    branches:
      - beta  # Triggers only when PRs into beta are closed

jobs:
  rebase-feature:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta branch
        uses: actions/checkout@v3
        with:
          ref: beta
          fetch-depth: 0  # Required for full history & rebase

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all remote branches
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Rebase beta onto merged feature branch
        run: |
          git rebase origin/${{ github.event.pull_request.head.ref }} beta || echo "Rebase failed"

      - name: Push updated beta
        run: |
          git push origin beta --force-with-lease
